"MY_EMAIL_ADDRESS": "<YOUR_EMAIL_ADDRESS>"
"MY_GMAIL_PASSWORD": "<YOUR_GMAIL_APP_PASSWORD>"
"GOOGLE_API_KEY": "<YOUR_GOOGLE_API_KEY>"
"OPENWEATHERMAP_API_KEY": "<YOUR_OPENWEATHERMAP_API_KEY>"
"OPENWEATHERMAP_GEOCODE_BASE_URL": "http://api.openweathermap.org/geo/1.0/direct"
"OPENWEATHERMAP_CURRENT_WEATHER_BASE_URL": "https://api.openweathermap.org/data/3.0/onecall"
"REDDIT_CLIENT_ID": "<YOUR_REDDIT_CLIENT_ID>"
"REDDIT_CLIENT_SECRET": "<YOUR_REDDIT_CLIENT_SECRET>"
"REDDIT_USERNAME": "<YOUR_REDDIT_USERNAME>"
"REDDIT_PASSWORD": "<YOUR_REDDIT_PASSWORD>"
"REDDIT_USER_AGENT": "<Your app>/1.0 by <Your Reddit Username>"
"TELEGRAM_BOT_TOKEN": "YOUR_TELEGRAM_BOT_TOKEN"
"TELEGRAM_CHAT_IDS": {"PERSON1":"CHAT_ID1"}
"MY_GARMIN_PASSWORD": "YOUR_GARMIN_ACCOUNT_PASSWORD"
"TWITTER_CONSUMER_KEY": "<YOUR_TWITTER_CONSUMER_KEY>"
"TWITTER_CONSUMER_SECRET": "<YOUR_TWITTER_CONSUMER_SECRET>"
"TWITTER_BEARER_TOKEN": "<YOUR_TWITTER_BEARER_TOKEN>"
"TWITTER_ACCESS_TOKEN": "<YOUR_TWITTER_ACCESS_TOKEN>"
"TWITTER_ACCESS_TOKEN_SECRET": "<YOUR_TWITTER_ACCESS_TOKEN_SECRET>"
