"MY_EMAIL_ADDRESS": "<YOUR_EMAIL_ADDRESS>"
"MY_GMAIL_PASSWORD": "<YOUR_GMAIL_APP_PASSWORD>"
"GOOGLE_API_KEY": "<YOUR_GOOGLE_API_KEY>"
"OPENWEATHERMAP_API_KEY": "<YOUR_OPENWEATHERMAP_API_KEY>"
"OPENWEATHERMAP_GEOCODE_BASE_URL": "http://api.openweathermap.org/geo/1.0/direct"
"OPENWEATHERMAP_CURRENT_WEATHER_BASE_URL": "https://api.openweathermap.org/data/3.0/onecall"
"REDDIT_CLIENT_ID": "<YOUR_REDDIT_CLIENT_ID>"
"REDDIT_CLIENT_SECRET": "<YOUR_REDDIT_CLIENT_SECRET>"
"REDDIT_USERNAME": "<YOUR_REDDIT_USERNAME>"
"REDDIT_PASSWORD": "<YOUR_REDDIT_PASSWORD>"
"REDDIT_USER_AGENT": "<Your app>/1.0 by <Your Reddit Username>"